export const AGREGAR_ORDEN   = 'AGREGAR_ORDEN';
export const EDITAR_ORDEN    = 'EDITAR_ORDEN';
export const ELIMINAR_ORDEN  = 'ELIMINAR_ORDEN';
export const SET_LISTA_ORDENES  = 'SET_LISTA_ORDENES';
export const REINICIAR_LISTA_ORDENES  = 'REINICIAR_LISTA_ORDENES';