
// export const OBTENER_AMBIENTES          = 'OBTENER_AMBIENTES';
// export const OBTENER_AMBIENTES_EXITO    = 'OBTENER_AMBIENTES_EXITO';
// export const OBTENER_AMBIENTES_LOADING = 'OBTENER_AMBIENTES_LOADING';
// export const OBTENER_AMBIENTES_ERROR    = 'OBTENER_AMBIENTES_ERROR';

export const OBTENER_PRODUCTOS          = 'OBTENER_PRODUCTOS';
export const OBTENER_PRODUCTOS_EXITO   = 'OBTENER_PRODUCTOS_EXITO';
export const OBTENER_PRODUCTOS_LOADING = 'OBTENER_PRODUCTOS_LOADING';
export const OBTENER_PRODUCTOS_ERROR    = 'OBTENER_PRODUCTOS_ERROR';